apiVersion: v1
kind: Pod
metadata:
  name: podasroot
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: shell
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
