apiVersion: v1
kind: Pod
metadata:
  name: podasusr
spec:
  securityContext:
    runAsUser: 1234
  containers:
  - name: shell
    image: alpine:3.7
    command:
      - "sh"
      - "-c"
      - "sleep 10001"
